// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "projectId": "prysm-v122-05135565-787d2",
  "appId": "1:35369720921:web:2b3aa61d1b0e3e99816548",
  "storageBucket": "prysm-v122-05135565-787d2.firebasestorage.app",
  "apiKey": "AIzaSyD-cfe3_eMxDW7U2Q0VPk_-CaBE01ghOSk",
  "authDomain": "prysm-v122-05135565-787d2.firebaseapp.com",
  "measurementId": "G-R9BJ8B19D3",
  "messagingSenderId": "35369720921"
};
